const express = require('express')
const load = require('./markovLoader.js')
const extractEmojis = require('./emojiExtractor.js')
const config = require('./config.js')
const createMarkovBot = require('./markovBot.js')
const createSlackBot = require('./slackBot.js')

const FILE_PATH = 'data/livvy_chat.txt'
const MAX_MESSAGE_LENGTH = 400
const SLACK_USERS = {
  U010DAFUAEQ: "Matt Jardine",
  U0103N3D4F3: "Olivia Ruiz-Knott",
  U0103DUNXPG: "both"
}

startup()

async function startup() {
  createMarkovBots(await load(FILE_PATH, MAX_MESSAGE_LENGTH))
  startServer(await extractEmojis(FILE_PATH))
}

async function createMarkovBots(lists) {
  for(user in SLACK_USERS) {
    let realName = SLACK_USERS[user]
    console.log('creating', realName)
    let responseGenerator = createMarkovBot(lists[realName])
    let slackName = user.replace('_', '-')
    createSlackBot(config[user], slackName, responseGenerator)
  }
}

function startServer(emojis) {
  const app = express()
  app.get('/ping', (req, res) => {
    return res.send('pong')
  })
  app.set('port', process.env.PORT || 5000)
  // serve the assets generated by webpack
  app.use(express.static('build'))
  // json emoji data
  app.get('/emoji-use', (req, res) => res.json(emojis))
  app.get('/', (req, res) => {
    res.sendFile(__dirname + '/build/index.html')
  })
  app.listen(app.get('port'), () => {
    console.log('Server is running on port', app.get('port'))
  })
}
